//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Call
    {
        public int id { get; set; }
        public int Customer { get; set; }
        public int Agent { get; set; }
        public string CallText { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> DateSolved { get; set; }
        public Nullable<System.DateTime> DateArchived { get; set; }
        public string Reason { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual CallStatus CallStatus { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
